services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"  # Expose port 8000
    networks:
      - backend
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    container_name: frontend
    build:
      context: ./client
    command: npm run dev
    volumes:
      - ./client:/usr/src/client
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      NODE_ENV: development

  mysql:
    image: mysql:8.0
    container_name: manage_invoice_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./datnan.sql:/docker-entrypoint-initdb.d/datnan.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_allowed_packet=128M
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - backend

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client:/usr/src/client
      - ./backend/public:/var/www/public
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - frontend
      - backend

volumes:
  dbdata:

networks:
  default:
    name: sail
  frontend:
    driver: bridge
  backend:
    driver: bridge
