<?php

namespace App\Support;

class DependentHelper
{
    const RELATIONSHIP_NAMES = [
        '01' => 'Con',
        '02' => 'Vợ/chồng',
        '03' => 'Cha/mẹ',
        '04' => 'Khác',
    ];

    const NATIONALITY_NAMES = [
        '01' => 'Việt Nam',
        '02' => 'Khác',
    ];

    const ROOT_ELEMENT_NAME = [
        'rootElementName' => 'HSoThueDTu',
        '_attributes' => [
            'xmlns:xsi' => 'http://www.w3.org/2001/XMLSchema-instance',
            'xmlns' => 'http://kekhaithue.gdt.gov.vn/TKhaiThue',
        ],
    ];

    const EMPTY_FIELD_KEYS = [
        'ct07', 'ct08', 'ct09', 'ct10', 'ct11',
        'ct12_ma', 'ct12', 'ct13', 'ct14_ma', 'ct14',
        'ct15', 'ct16', 'ct17_ma', 'ct17', 'ct18_ma',
        'ct18', 'ct19_ma', 'ct19', 'ct20_ma', 'ct20',
        'ct21', 'ct22', 'ct23'
    ];

    public static function XML_Schema($kyKKhai, $client)
    {
        $today = date('Y-m-d');

        return [
            'HSoKhaiThue' => [
                '_attributes' => [
                    'id' => 'ID_1',
                ],
                'TTinChung' => [
                    'TTinDVu' => [
                        'maDVu' => 'HTKK',
                        'tenDVu' => 'HỖ TRỢ KÊ KHAI THUẾ',
                        'pbanDVu' => '5.0.9',
                        'ttinNhaCCapDVu' => '80BC944EC50010324DD58BAFD05D49E7',
                    ],
                    'TTinTKhaiThue' => [
                        'TKhaiThue' => self::generateTKhaiThueData($kyKKhai, $client, $today),
                        'NNT' => self::generateNNTData($client),
                    ],
                ],
                'CTieuTKhaiChinh' => [
                    'CapMSTChoNPT' => ['BKeCapMSTChoNPT' => []],
                    'ThayDoiTTinNPT' => ['BKeThayDoiTTinNPT' => []],
                ],
            ],
        ];
    }

    public static function xmlWithComment($content)
    {
        $comment = '<!-- XML file generated by Terra v2023 (https://terra-plat.vn) -->';
        $formattedXml = self::formatXML($content);

        return str_replace('<?xml version="1.0" encoding="UTF-8"?>', "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n$comment", $formattedXml);
    }

    private static function formatXML($content)
    {
        $doc = new \DOMDocument('1.0', 'UTF-8');
        $doc->preserveWhiteSpace = false;
        $doc->formatOutput = true;
        $doc->loadXML($content);

        return $doc->saveXML();
    }

    private static function generateTKhaiThueData($kyKKhai, $client, $today)
    {
        return [
            'maTKhai' => '302',
            'tenTKhai' => 'BẢNG TỔNG HỢP ĐĂNG KÝ NGƯỜI PHỤ THUỘC GIẢM TRỪ GIA CẢNH',
            'moTaBMau' => '(Ban hành kèm theo Thông tư số 156/2013/TT-BTC ngày 06/11/2013 của Bộ Tài chính)',
            'pbanTKhaiXML' => '2.0.6',
            'loaiTKhai' => 'C',
            'soLan' => 1,
            'KyKKhaiThue' => [
                'kieuKy' => 'Y',
                'kyKKhai' => $kyKKhai,
                'kyKKhaiTuNgay' => "01/01/$kyKKhai",
                'kyKKhaiDenNgay' => "31/12/$kyKKhai",
                'kyKKhaiTuThang' => null,
                'kyKKhaiDenThang' => null,
            ],
            'maCQTNoiNop' => $client->tax_office_district_code,
            'tenCQTNoiNop' => $client->tax_office_district_name,
            'ngayLapTKhai' => $today,
            'GiaHan' => ['maLyDoGiaHan' => null, 'lyDoGiaHan' => null],
            'nguoiKy' => $client->presenter_name,
            'ngayKy' => $today,
            'nganhNgheKD' => null,
        ];
    }

    private static function generateNNTData($client)
    {
        return [
            'mst' => $client->pit_declaration_company_tax_code,
            'tenNNT' => $client->company_name,
            'dchiNNT' => $client->address,
            'phuongXa' => null,
            'maHuyenNNT' => $client->pit_declaration_district_code,
            'tenHuyenNNT' => $client->pit_declaration_district_name,
            'maTinhNNT' => $client->pit_declaration_province_code,
            'tenTinhNNT' => $client->pit_declaration_province_name,
            'dthoaiNNT' => $client->company_contact_phone,
            'faxNNT' => $client->company_contact_fax,
            'emailNNT' => $client->company_contact_email,
        ];
    }
}
