<?php

namespace App\Support;

class Sensitive
{

    const BASIC_DATA = [
        "id" => "id",
        "full_name" => "full_name",
        "code" => "code",
        "department" => "department",
        "client_department_id" => "client_department_id",
        "position" => "position",
        "client_position_id" => "client_position_id",
        "title" => "title",
        "workplace" => "workplace",
        "user_id" => "user_id",
        "role" => "role"
    ];

    const PERSONAL_DATA = [
        "probation_start_date" => "probation_start_date",
        "probation_end_date" => "probation_end_date",
        "official_contract_signing_date" => "official_contract_signing_date",
        "type_of_employment_contract" => "type_of_employment_contract",
        "bank_account" => "bank_account",
        "bank_code" => "bank_code",
        "bank_account_number" => "bank_account_number",
        "bank_name" => "bank_name",
        "bank_branch" => "bank_branch",
        "social_insurance_number" => "social_insurance_number",
        "date_of_birth" => "date_of_birth",
        "sex" => "sex",
        "marital_status" => "marital_status",
        "medical_care_hospital_name" => "medical_care_hospital_name",
        "medical_care_hospital_code" => "medical_care_hospital_code",
        "nationality" => "nationality",
        "nation" => "nation",
        "id_card_number" => "id_card_number",
        "is_card_issue_date" => "is_card_issue_date",
        "id_card_issue_place" =>  "id_card_issue_place",
        "birth_place_address" => "birth_place_address",
        "birth_place_street" => "birth_place_street",
        "birth_place_wards" => "birth_place_wards",
        "birth_place_district" => "birth_place_district",
        "birth_place_city_province" => "birth_place_city_province",
        "resident_address" => "resident_address",
        "resident_street" => "resident_street",
        "resident_wards" => "resident_wards",
        "resident_district" => "resident_district",
        "resident_city_province" => "resident_city_province",
        "contact_address" => "contact_address",
        "contact_street" => "contact_street",
        "contact_wards" => "contact_wards",
        "contact_district" => "contact_district",
        "contact_city_province" => "contact_city_province",
        "contact_phone_number" => "contact_phone_number",
        "contract_no" => "contract_no",
        "household_head_info" => "household_head_info",
        "household_code" => "household_code",
        "household_head_fullname" => "household_head_fullname",
        "household_head_id_card_number" => "household_head_id_card_number",
        "household_head_date_of_birth" => "household_head_date_of_birth",
        "household_head_relation" => "household_head_relation",
        "household_head_phone" => "household_head_phone",
        "resident_record_number" => "resident_record_number",
        "resident_record_type" => "resident_record_type",
        "resident_village" => "resident_village",
        "resident_commune_ward_district_province" => "resident_commune_ward_district_province",
        "resident_status" => "resident_status",
        "status" => "status",
        "quitted_at" => "quitted_at",
        "deleted_at" => "deleted_at",
        "created_at" => "created_at",
        "updated_at" => "updated_at",
        "foreigner_job_position" => "foreigner_job_position",
        "foreigner_contract_status" => "foreigner_contract_status",
        "education_level" => "education_level",
        "work_schedule_group_template_id" => "work_schedule_group_template_id",
        "year_paid_leave_count" => "year_paid_leave_count",
        "currency" => "currency",
        "mst_code" => "mst_code",
        "career" => "career",
        "checkin_wifi" => "checkin_wifi",
        "checkin_camera" => "checkin_camera",
        "checkin_input" => "checkin_input",
        "timesheet_exception" => "timesheet_exception",
        "case_import_paidleave" => "case_import_paidleave",
        "start_import_paidleave" => "start_import_paidleave",
        "started_import_paidleave" => "started_import_paidleave",
        "hours_import_paidleave" => "hours_import_paidleave",
        "date_of_entry" => "date_of_entry",
        "religion" => "religion",
        "blood_group" => "blood_group",
        "spouse_working_at_company" => "spouse_working_at_company",
        "educational_qualification" => "educational_qualification",
        "year_of_graduation" => "year_of_graduation",
        "major" => "major",
        "certificate_1" => "certificate_1",
        "certificate_2" => "certificate_2",
        "certificate_3" => "certificate_3",
        "certificate_4" => "certificate_4",
        "certificate_5" => "certificate_5",
        "certificate_6" => "certificate_6",
        "emergency_contact_name" => "emergency_contact_name",
        "emergency_contact_relationship" => "emergency_contact_relationship",
        "emergency_contact_phone" => "emergency_contact_phone",
        "commuting_transportation" => "commuting_transportation",
        "vehicle_license_plate" => "vehicle_license_plate",
        "locker_number" => "locker_number",
        "number_of_dependents" => "number_of_dependents",
        "effective_date_of_social_insurance" => "effective_date_of_social_insurance",
        "is_insurance_applicable" => "is_insurance_applicable",
        "is_tax_applicable" => "is_tax_applicable"
    ];

    const SALARY = [
        "salary" => "salary",
        "allowance_for_responsibilities" => "allowance_for_responsibilities",
        "fixed_allowance" => "fixed_allowance",
        "salary_for_social_insurance_payment" => "salary_for_social_insurance_payment",
        "hour_wage" => "hour_wage",
        "is_involved_payroll" => "is_involved_payroll"
    ];
}
